import { renderSvg } from "@/lib/engine/render";
import type { Direction, RenderOptions } from "@/lib/engine/types";
import { cn } from "@/lib/utils";

/**
 * Renders a document at any size. The markup is generated by the renderer — the
 * same string that becomes the exported SVG — so preview and export are provably
 * the same artwork.
 *
 * `corners` defaults to `rounded` here, unlike the renderer's own default of
 * `square`. The split is deliberate: this component *displays* a plate, and a
 * plate is designed with corners; the exporter builds the platform files, which
 * are square because the platform masks them itself. Anything that means "this is
 * the file that ships" should say `corners: "square"` out loud.
 */
export function IconTile({
  direction,
  className,
  watermark,
  uid,
  title,
  fit,
  corners = "rounded",
  radius,
  layers,
}: {
  direction: Direction;
  className?: string;
  watermark?: boolean;
  uid?: string;
  title?: string;
  /**
   * Scale the artwork to a platform's safe area. The studio passes the same
   * value here that the export uses, so the preview is what gets downloaded.
   */
  fit?: number;
  /** `rounded` is the design look; `square` is the platform master. */
  corners?: RenderOptions["corners"];
  /** Overrides the document's own radius when `corners: "rounded"`. */
  radius?: number;
  /** Which plate layers to paint, for previewing an Android adaptive layer. */
  layers?: RenderOptions["layers"];
}) {
  const options: RenderOptions = { watermark, uid, fit, corners, radius, layers };
  const svg = renderSvg(direction, options);

  return (
    <div
      className={cn(
        "aspect-square w-full [&>svg]:block [&>svg]:h-full [&>svg]:w-full",
        className,
      )}
      title={title}
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
