import { IconTile } from "@/components/icon-tile";
import { paletteById } from "@/lib/engine/palettes";
import { DEFAULT_RADIUS, type Direction } from "@/lib/engine/types";
import { cn } from "@/lib/utils";

/**
 * The Puff mark, drawn by the same renderer as everything else in the product.
 *
 * Rendering the logo rather than shipping a file is not a gimmick: it means the
 * mark on the landing page is generated by the exact code path a user's plate
 * takes, so a regression in the renderer shows up here rather than being found by
 * the first customer.
 *
 * It is a *plate with nothing on it*, which is the honest brand for this product
 * now: the app no longer draws a mark of its own, and pretending otherwise would
 * mean the logo demonstrated a feature the studio had removed. No artwork means
 * no upload is needed to render it, and the electric look is the one that carries
 * the reference's rim at 24px.
 */
const BRAND: Direction = {
  palette: paletteById("electric-blue"),
  finish: { shadow: 0.55, grain: 0.1 },
  radius: DEFAULT_RADIUS,
  title: "Puff Studio",
  seedHint: 2052,
};

export function Logo({ className }: { className?: string }) {
  return (
    <span
      data-slot="logo"
      className={cn("inline-flex items-center gap-2", className)}
    >
      <span className="block w-6 shrink-0">
        <IconTile direction={BRAND} uid="puffmark" title="Puff Studio" />
      </span>
      <span className="font-display text-sm font-medium tracking-tight">
        Puff Studio
      </span>
    </span>
  );
}
