import { paletteById } from "./engine/palettes";
import { DEFAULT_RADIUS, type Direction } from "./engine/types";

/**
 * The Puff mark, as a document.
 *
 * This lives in `lib/` rather than beside the component that draws it because
 * three things need the *same* document: the landing header, the studio's own
 * logo link, and `scripts/gen-brand-assets.mjs`, which rasterizes the favicon,
 * the touch icon and the social card from this exact direction. A second copy of
 * these five fields is how a favicon ends up a different blue than the logo
 * beside it.
 *
 * Rendering the logo rather than shipping a bitmap is not a gimmick: it means the
 * mark on the landing page is generated by the exact code path a user's plate
 * takes, so a regression in the renderer shows up here rather than being found by
 * the first customer.
 *
 * It is a *plate with nothing on it*, which is the honest brand for this product
 * now: the app no longer draws a mark of its own, and pretending otherwise would
 * mean the logo demonstrated a feature the studio had removed. No artwork means no
 * upload is needed to render it, and the electric look is the one that carries the
 * reference's rim at 24px.
 */
export const BRAND: Direction = {
  palette: paletteById("electric-blue"),
  finish: { shadow: 0.55, grain: 0.1 },
  radius: DEFAULT_RADIUS,
  title: "Puff Studio",
  seedHint: 2052,
};

/** The filter/gradient id the brand plate renders under. Stable by hand. */
export const BRAND_UID = "puffmark";
